INSERT INTO userr (username, "password", "name", email, last_login_ts, deleted, "locked", one_log_pwd,
                   profile_picture, created_by, last_modified_by, created_date, last_modified_date)
VALUES ('f.pena', '$2a$10$8c76Jfm15Ib7IOVh7l1DJOKtKUxeHvSlE/oj39W3uKbNyS3oK7BbK', 'Freddy Peña',
        'me@fredpena.dev', NULL, FALSE, FALSE, FALSE, NULL, 'root', 'root', NOW(), NOW());


INSERT INTO person(first_name, last_name, email, phone, date_of_birth, occupation, role, important, created_by,
                   last_modified_by, created_date, last_modified_date)
VALUES ('Jeremy', 'Marilli', 'jeremy.marilli@vesa.pf', '(526) 435-1819', '1983-09-07', 'Chief Projectionist',
        'External', false, 'root', 'root', NOW(), NOW()),
       ('Kathryn', 'Huet', 'kathryn.huet@wupikdoh.by', '(937) 855-5936', '1927-02-24', 'Telecasting Engineer',
        'Worker', false, 'root', 'root', NOW(), NOW()),
       ('Lelia', 'Matsuo', 'lelia.matsuo@dajsiphaj.az', '(960) 335-6192', '1935-03-07', 'Drama Therapist',
        'Supervisor', true, 'root', 'root', NOW(), NOW()),
       ('Virginia', 'Woods', 'virginia.woods@soofpe.ht', '(735) 809-2611', '1954-12-13',
        'General Superintendent', 'Manager', false, 'root', 'root', NOW(), NOW()),
       ('Sally', 'Aoki', 'sally.aoki@aruzusjas.tc', '(857) 797-7918', '1937-02-13', 'Technical Communicator',
        'External', true, 'root', 'root', NOW(), NOW()),
       ('Isabelle', 'de Ridder', 'isabelle.deridder@ufeco.in', '(659) 331-1543', '1962-11-30',
        'Leisure Studies Professor', 'Worker', false, 'root', 'root', NOW(), NOW()),
       ('Rosie', 'Murphy', 'rosie.murphy@uneehi.id', '(759) 639-8597', '1958-06-02',
        'Air Conditioning Service Technician', 'Supervisor', false, 'root', 'root', NOW(), NOW()),
       ('Lou', 'Meyer', 'lou.meyer@hahinaba.gm', '(942) 352-4854', '1929-02-25', 'Business Unit Manager',
        'External', true, 'root', 'root', NOW(), NOW()),
       ('Rodney', 'Love', 'rodney.love@zun.ph', '(247) 867-8287', '2012-06-21', 'Job Estimator', 'Worker',
        false, 'root', 'root', NOW(), NOW()),
       ('Kenneth', 'Bianchini', 'kenneth.bianchini@jo.ws', '(302) 793-9936', '2001-06-13',
        'Correctional Officer Sergeant', 'Worker', false, 'root', 'root', NOW(), NOW()),
       ('Essie', 'Dietrich', 'essie.dietrich@goltuefo.mn', '(861) 740-6628', '1939-02-13',
        'Parking Meter Collector', 'Supervisor', false, 'root', 'root', NOW(), NOW()),
       ('Leila', 'Simon', 'leila.simon@lupuwuzo.gw', '(953) 866-9992', '1930-11-10',
        'Signals Intelligence/Electronic Warfare Chief', 'External', false, 'root', 'root', NOW(), NOW()),
       ('Eva', 'Pierre', 'eva.pierre@reduzris.ee', '(915) 491-8384', '1927-11-22', 'Clinical Psychiatrist',
        'Worker', true, 'root', 'root', NOW(), NOW()),
       ('Landon', 'Moretti', 'landon.moretti@pubsav.sk', '(584) 909-6235', '1981-02-24', 'Wildlife Officer',
        'Supervisor', false, 'root', 'root', NOW(), NOW()),
       ('Mittie', 'Sardi', 'mittie.sardi@lullip.nf', '(673) 849-4256', '1973-08-04', 'Food Chemist', 'Manager',
        false, 'root', 'root', NOW(), NOW()),
       ('Corey', 'McDaniel', 'corey.mcdaniel@aba.tc', '(268) 208-9643', '2012-10-08',
        'Advanced Foreign Counterintelligence Specialist (Afcs)', 'Supervisor', false, 'root', 'root', NOW(), NOW()),
       ('Hester', 'Stein', 'hester.stein@kettujwo.eu', '(873) 489-6641', '1939-08-01', 'Forest Fire Officer',
        'Manager', false, 'root', 'root', NOW(), NOW()),
       ('Danny', 'Lowe', 'danny.lowe@ju.sd', '(243) 974-5539', '2013-11-13', 'Catalogue Illustrator', 'External',
        true, 'root', 'root', NOW(), NOW()),
       ('Lillie', 'Winter', 'lillie.winter@vioburez.vi', '(816) 699-1291', '1945-10-08', 'Knife Grinder',
        'Worker', false, 'root', 'root', NOW(), NOW()),
       ('Brandon', 'Borchi', 'brandon.borchi@ig.al', '(319) 401-1090', '2000-07-30', 'Neuropsychiatrist',
        'Supervisor', false, 'root', 'root', NOW(), NOW()),
       ('Isaac', 'Bernardi', 'isaac.bernardi@omu.bj', '(359) 691-6408', '2002-01-10', 'Bottle Packer', 'Manager',
        false, 'root', 'root', NOW(), NOW()),
       ('Clyde', 'Crawford', 'clyde.crawford@luw.dz', '(273) 892-4646', '2019-01-13',
        'Special Education Kindergarten Teacher', 'External', true, 'root', 'root', NOW(), NOW()),
       ('Paul', 'Sherman', 'paul.sherman@pi.cf', '(304) 610-2881', '2008-06-21', 'Commercial Art Instructor',
        'Worker', false, 'root', 'root', NOW(), NOW()),
       ('Craig', 'Russell', 'craig.russell@zu.nz', '(237) 969-2900', '2020-04-18', 'Ferryboat Captain',
        'Supervisor', true, 'root', 'root', NOW(), NOW()),
       ('John', 'Sutton', 'john.sutton@ag.ee', '(207) 424-6468', '2013-06-30', 'School Social Worker', 'Manager',
        false, 'root', 'root', NOW(), NOW()),
       ('Francisco', 'Formigli', 'francisco.formigli@fopav.tn', '(481) 661-8179', '1990-06-14',
        'Joint Terminal Attack Controller', 'External', false, 'root', 'root', NOW(), NOW()),
       ('Gary', 'Baker', 'gary.baker@ji.cf', '(212) 510-3444', '2022-07-04', 'VP Sales', 'Worker', true, 'root', 'root',
        NOW(), NOW()),
       ('Earl', 'Giovannoni', 'earl.giovannoni@lojet.ge', '(433) 862-3076', '1987-11-12',
        'Auto Service Station Attendant', 'Manager', false, 'root', 'root', NOW(), NOW()),
       ('Helen', 'Zanieri', 'helen.zanieri@ukve.tn', '(619) 506-4452', '1969-03-26', 'Healthcare Social Worker',
        'External', false, 'root', 'root', NOW(), NOW()),
       ('Agnes', 'Toccafondi', 'agnes.toccafondi@viipo.ae', '(616) 688-6883', '1971-04-15', 'Comedian',
        'External', false, 'root', 'root', NOW(), NOW());